/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 59
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 61
#define ALIAS_COUNT 0
#define TOKEN_COUNT 40
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_keyword = 1,
  anon_sym_EQ = 2,
  anon_sym_SEMI = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  sym_label = 6,
  sym_variable = 7,
  anon_sym_every = 8,
  anon_sym_at = 9,
  sym_number = 10,
  anon_sym_frame = 11,
  anon_sym_frames = 12,
  anon_sym_s = 13,
  anon_sym_second = 14,
  anon_sym_seconds = 15,
  anon_sym_ms = 16,
  anon_sym_millisecond = 17,
  anon_sym_milliseconds = 18,
  anon_sym_LPAREN = 19,
  anon_sym_COMMA = 20,
  anon_sym_RPAREN = 21,
  anon_sym_LBRACK = 22,
  anon_sym_RBRACK = 23,
  anon_sym_up = 24,
  anon_sym_down = 25,
  anon_sym_left = 26,
  anon_sym_right = 27,
  sym_color_value = 28,
  anon_sym_red = 29,
  anon_sym_green = 30,
  anon_sym_blue = 31,
  anon_sym_yellow = 32,
  anon_sym_black = 33,
  anon_sym_brown = 34,
  anon_sym_cyan = 35,
  anon_sym_purple = 36,
  anon_sym_orange = 37,
  anon_sym_white = 38,
  anon_sym_pink = 39,
  sym_source_file = 40,
  sym__stmt = 41,
  sym_action = 42,
  sym_var_definition = 43,
  sym_declaration = 44,
  sym_component_declaration = 45,
  sym_trigger = 46,
  sym_events = 47,
  sym_sequence = 48,
  sym_repeat_quantifier = 49,
  sym_time_unit = 50,
  sym_position = 51,
  sym_vector = 52,
  sym_direction = 53,
  sym_color = 54,
  sym_value = 55,
  sym_color_name = 56,
  aux_sym_source_file_repeat1 = 57,
  aux_sym_events_repeat1 = 58,
  aux_sym_sequence_repeat1 = 59,
  aux_sym_vector_repeat1 = 60,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_keyword] = "keyword",
  [anon_sym_EQ] = "=",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_label] = "label",
  [sym_variable] = "variable",
  [anon_sym_every] = "every",
  [anon_sym_at] = "at",
  [sym_number] = "number",
  [anon_sym_frame] = "frame",
  [anon_sym_frames] = "frames",
  [anon_sym_s] = "s",
  [anon_sym_second] = "second",
  [anon_sym_seconds] = "seconds",
  [anon_sym_ms] = "ms",
  [anon_sym_millisecond] = "millisecond",
  [anon_sym_milliseconds] = "milliseconds",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_up] = "up",
  [anon_sym_down] = "down",
  [anon_sym_left] = "left",
  [anon_sym_right] = "right",
  [sym_color_value] = "color_value",
  [anon_sym_red] = "red",
  [anon_sym_green] = "green",
  [anon_sym_blue] = "blue",
  [anon_sym_yellow] = "yellow",
  [anon_sym_black] = "black",
  [anon_sym_brown] = "brown",
  [anon_sym_cyan] = "cyan",
  [anon_sym_purple] = "purple",
  [anon_sym_orange] = "orange",
  [anon_sym_white] = "white",
  [anon_sym_pink] = "pink",
  [sym_source_file] = "source_file",
  [sym__stmt] = "_stmt",
  [sym_action] = "action",
  [sym_var_definition] = "var_definition",
  [sym_declaration] = "declaration",
  [sym_component_declaration] = "component_declaration",
  [sym_trigger] = "trigger",
  [sym_events] = "events",
  [sym_sequence] = "sequence",
  [sym_repeat_quantifier] = "repeat_quantifier",
  [sym_time_unit] = "time_unit",
  [sym_position] = "position",
  [sym_vector] = "vector",
  [sym_direction] = "direction",
  [sym_color] = "color",
  [sym_value] = "value",
  [sym_color_name] = "color_name",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_events_repeat1] = "events_repeat1",
  [aux_sym_sequence_repeat1] = "sequence_repeat1",
  [aux_sym_vector_repeat1] = "vector_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_keyword] = sym_keyword,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_label] = sym_label,
  [sym_variable] = sym_variable,
  [anon_sym_every] = anon_sym_every,
  [anon_sym_at] = anon_sym_at,
  [sym_number] = sym_number,
  [anon_sym_frame] = anon_sym_frame,
  [anon_sym_frames] = anon_sym_frames,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_second] = anon_sym_second,
  [anon_sym_seconds] = anon_sym_seconds,
  [anon_sym_ms] = anon_sym_ms,
  [anon_sym_millisecond] = anon_sym_millisecond,
  [anon_sym_milliseconds] = anon_sym_milliseconds,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_up] = anon_sym_up,
  [anon_sym_down] = anon_sym_down,
  [anon_sym_left] = anon_sym_left,
  [anon_sym_right] = anon_sym_right,
  [sym_color_value] = sym_color_value,
  [anon_sym_red] = anon_sym_red,
  [anon_sym_green] = anon_sym_green,
  [anon_sym_blue] = anon_sym_blue,
  [anon_sym_yellow] = anon_sym_yellow,
  [anon_sym_black] = anon_sym_black,
  [anon_sym_brown] = anon_sym_brown,
  [anon_sym_cyan] = anon_sym_cyan,
  [anon_sym_purple] = anon_sym_purple,
  [anon_sym_orange] = anon_sym_orange,
  [anon_sym_white] = anon_sym_white,
  [anon_sym_pink] = anon_sym_pink,
  [sym_source_file] = sym_source_file,
  [sym__stmt] = sym__stmt,
  [sym_action] = sym_action,
  [sym_var_definition] = sym_var_definition,
  [sym_declaration] = sym_declaration,
  [sym_component_declaration] = sym_component_declaration,
  [sym_trigger] = sym_trigger,
  [sym_events] = sym_events,
  [sym_sequence] = sym_sequence,
  [sym_repeat_quantifier] = sym_repeat_quantifier,
  [sym_time_unit] = sym_time_unit,
  [sym_position] = sym_position,
  [sym_vector] = sym_vector,
  [sym_direction] = sym_direction,
  [sym_color] = sym_color,
  [sym_value] = sym_value,
  [sym_color_name] = sym_color_name,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_events_repeat1] = aux_sym_events_repeat1,
  [aux_sym_sequence_repeat1] = aux_sym_sequence_repeat1,
  [aux_sym_vector_repeat1] = aux_sym_vector_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_every] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_at] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_frame] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_frames] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_second] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seconds] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ms] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_millisecond] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_milliseconds] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_up] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_down] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_left] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_right] = {
    .visible = true,
    .named = false,
  },
  [sym_color_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_red] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_green] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_blue] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_yellow] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_black] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_brown] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cyan] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_purple] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_orange] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_white] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pink] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__stmt] = {
    .visible = false,
    .named = true,
  },
  [sym_action] = {
    .visible = true,
    .named = true,
  },
  [sym_var_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_component_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_trigger] = {
    .visible = true,
    .named = true,
  },
  [sym_events] = {
    .visible = true,
    .named = true,
  },
  [sym_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_repeat_quantifier] = {
    .visible = true,
    .named = true,
  },
  [sym_time_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_position] = {
    .visible = true,
    .named = true,
  },
  [sym_vector] = {
    .visible = true,
    .named = true,
  },
  [sym_direction] = {
    .visible = true,
    .named = true,
  },
  [sym_color] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_color_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_events_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_vector_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_component = 1,
  field_frame = 2,
  field_lhs = 3,
  field_millisecond = 4,
  field_onetime = 5,
  field_operation = 6,
  field_repeated = 7,
  field_second = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_component] = "component",
  [field_frame] = "frame",
  [field_lhs] = "lhs",
  [field_millisecond] = "millisecond",
  [field_onetime] = "onetime",
  [field_operation] = "operation",
  [field_repeated] = "repeated",
  [field_second] = "second",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 2},
  [7] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_repeated, 0},
  [1] =
    {field_onetime, 0},
  [2] =
    {field_frame, 0},
  [3] =
    {field_second, 0},
  [4] =
    {field_millisecond, 0},
  [5] =
    {field_component, 2},
    {field_lhs, 0},
  [7] =
    {field_lhs, 0},
    {field_operation, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      ADVANCE_MAP(
        '#', 6,
        '$', 7,
        '(', 18,
        ')', 20,
        ',', 19,
        ';', 11,
        '=', 10,
        '@', 8,
        '[', 21,
        ']', 22,
        '{', 12,
        '}', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 1:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(1);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(2);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(3);
      END_STATE();
    case 5:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(4);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_label);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_keyword);
      if (('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_variable);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_color_value);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'a', 1,
        'b', 2,
        'c', 3,
        'd', 4,
        'e', 5,
        'f', 6,
        'g', 7,
        'l', 8,
        'm', 9,
        'o', 10,
        'p', 11,
        'r', 12,
        's', 13,
        'u', 14,
        'w', 15,
        'y', 16,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 2:
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == 'y') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(26);
      if (lookahead == 's') ADVANCE(27);
      END_STATE();
    case 10:
      if (lookahead == 'r') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(29);
      if (lookahead == 'u') ADVANCE(30);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_s);
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 14:
      if (lookahead == 'p') ADVANCE(34);
      END_STATE();
    case 15:
      if (lookahead == 'h') ADVANCE(35);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_at);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(37);
      if (lookahead == 'u') ADVANCE(38);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 20:
      if (lookahead == 'a') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'w') ADVANCE(41);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(43);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(44);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(46);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_ms);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(47);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 30:
      if (lookahead == 'r') ADVANCE(49);
      END_STATE();
    case 31:
      if (lookahead == 'd') ADVANCE(50);
      END_STATE();
    case 32:
      if (lookahead == 'g') ADVANCE(51);
      END_STATE();
    case 33:
      if (lookahead == 'c') ADVANCE(52);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_up);
      END_STATE();
    case 35:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 36:
      if (lookahead == 'l') ADVANCE(54);
      END_STATE();
    case 37:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 39:
      if (lookahead == 'w') ADVANCE(57);
      END_STATE();
    case 40:
      if (lookahead == 'n') ADVANCE(58);
      END_STATE();
    case 41:
      if (lookahead == 'n') ADVANCE(59);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 43:
      if (lookahead == 'm') ADVANCE(61);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(63);
      END_STATE();
    case 46:
      if (lookahead == 'l') ADVANCE(64);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(65);
      END_STATE();
    case 48:
      if (lookahead == 'k') ADVANCE(66);
      END_STATE();
    case 49:
      if (lookahead == 'p') ADVANCE(67);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_red);
      END_STATE();
    case 51:
      if (lookahead == 'h') ADVANCE(68);
      END_STATE();
    case 52:
      if (lookahead == 'o') ADVANCE(69);
      END_STATE();
    case 53:
      if (lookahead == 't') ADVANCE(70);
      END_STATE();
    case 54:
      if (lookahead == 'l') ADVANCE(71);
      END_STATE();
    case 55:
      if (lookahead == 'k') ADVANCE(72);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_blue);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(73);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_cyan);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_down);
      END_STATE();
    case 60:
      if (lookahead == 'y') ADVANCE(74);
      END_STATE();
    case 61:
      if (lookahead == 'e') ADVANCE(75);
      END_STATE();
    case 62:
      if (lookahead == 'n') ADVANCE(76);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_left);
      END_STATE();
    case 64:
      if (lookahead == 'i') ADVANCE(77);
      END_STATE();
    case 65:
      if (lookahead == 'g') ADVANCE(78);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_pink);
      END_STATE();
    case 67:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 68:
      if (lookahead == 't') ADVANCE(80);
      END_STATE();
    case 69:
      if (lookahead == 'n') ADVANCE(81);
      END_STATE();
    case 70:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 71:
      if (lookahead == 'o') ADVANCE(83);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_black);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_brown);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_every);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_frame);
      if (lookahead == 's') ADVANCE(84);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_green);
      END_STATE();
    case 77:
      if (lookahead == 's') ADVANCE(85);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(86);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_right);
      END_STATE();
    case 81:
      if (lookahead == 'd') ADVANCE(88);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_white);
      END_STATE();
    case 83:
      if (lookahead == 'w') ADVANCE(89);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_frames);
      END_STATE();
    case 85:
      if (lookahead == 'e') ADVANCE(90);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_orange);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_purple);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_second);
      if (lookahead == 's') ADVANCE(91);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_yellow);
      END_STATE();
    case 90:
      if (lookahead == 'c') ADVANCE(92);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_seconds);
      END_STATE();
    case 92:
      if (lookahead == 'o') ADVANCE(93);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(94);
      END_STATE();
    case 94:
      if (lookahead == 'd') ADVANCE(95);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_millisecond);
      if (lookahead == 's') ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_milliseconds);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [anon_sym_every] = ACTIONS(1),
    [anon_sym_at] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_frame] = ACTIONS(1),
    [anon_sym_frames] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_second] = ACTIONS(1),
    [anon_sym_seconds] = ACTIONS(1),
    [anon_sym_ms] = ACTIONS(1),
    [anon_sym_millisecond] = ACTIONS(1),
    [anon_sym_milliseconds] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_up] = ACTIONS(1),
    [anon_sym_down] = ACTIONS(1),
    [anon_sym_left] = ACTIONS(1),
    [anon_sym_right] = ACTIONS(1),
    [sym_color_value] = ACTIONS(1),
    [anon_sym_red] = ACTIONS(1),
    [anon_sym_green] = ACTIONS(1),
    [anon_sym_blue] = ACTIONS(1),
    [anon_sym_yellow] = ACTIONS(1),
    [anon_sym_black] = ACTIONS(1),
    [anon_sym_brown] = ACTIONS(1),
    [anon_sym_cyan] = ACTIONS(1),
    [anon_sym_purple] = ACTIONS(1),
    [anon_sym_orange] = ACTIONS(1),
    [anon_sym_white] = ACTIONS(1),
    [anon_sym_pink] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(54),
    [sym__stmt] = STATE(5),
    [sym_action] = STATE(5),
    [sym_var_definition] = STATE(5),
    [sym_declaration] = STATE(5),
    [sym_trigger] = STATE(8),
    [sym_sequence] = STATE(57),
    [sym_repeat_quantifier] = STATE(41),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_sequence_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_keyword] = ACTIONS(5),
    [sym_label] = ACTIONS(7),
    [sym_variable] = ACTIONS(9),
    [anon_sym_every] = ACTIONS(11),
    [anon_sym_at] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym__stmt] = STATE(2),
    [sym_action] = STATE(2),
    [sym_var_definition] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_trigger] = STATE(8),
    [sym_sequence] = STATE(57),
    [sym_repeat_quantifier] = STATE(41),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_sequence_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym_keyword] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_label] = ACTIONS(32),
    [sym_variable] = ACTIONS(35),
    [anon_sym_every] = ACTIONS(38),
    [anon_sym_at] = ACTIONS(41),
    [sym_number] = ACTIONS(44),
    [anon_sym_LPAREN] = ACTIONS(47),
    [anon_sym_LBRACK] = ACTIONS(50),
    [anon_sym_up] = ACTIONS(53),
    [anon_sym_down] = ACTIONS(53),
    [anon_sym_left] = ACTIONS(53),
    [anon_sym_right] = ACTIONS(53),
    [sym_color_value] = ACTIONS(56),
    [anon_sym_red] = ACTIONS(59),
    [anon_sym_green] = ACTIONS(59),
    [anon_sym_blue] = ACTIONS(59),
    [anon_sym_yellow] = ACTIONS(59),
    [anon_sym_black] = ACTIONS(59),
    [anon_sym_brown] = ACTIONS(59),
    [anon_sym_cyan] = ACTIONS(59),
    [anon_sym_purple] = ACTIONS(59),
    [anon_sym_orange] = ACTIONS(59),
    [anon_sym_white] = ACTIONS(59),
    [anon_sym_pink] = ACTIONS(59),
  },
  [STATE(3)] = {
    [sym__stmt] = STATE(4),
    [sym_action] = STATE(4),
    [sym_var_definition] = STATE(4),
    [sym_declaration] = STATE(4),
    [sym_trigger] = STATE(8),
    [sym_sequence] = STATE(49),
    [sym_repeat_quantifier] = STATE(41),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_events_repeat1] = STATE(11),
    [aux_sym_sequence_repeat1] = STATE(13),
    [sym_keyword] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(62),
    [sym_label] = ACTIONS(7),
    [sym_variable] = ACTIONS(9),
    [anon_sym_every] = ACTIONS(11),
    [anon_sym_at] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(4)] = {
    [sym__stmt] = STATE(2),
    [sym_action] = STATE(2),
    [sym_var_definition] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_trigger] = STATE(8),
    [sym_sequence] = STATE(57),
    [sym_repeat_quantifier] = STATE(41),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_sequence_repeat1] = STATE(13),
    [sym_keyword] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(64),
    [sym_label] = ACTIONS(7),
    [sym_variable] = ACTIONS(9),
    [anon_sym_every] = ACTIONS(11),
    [anon_sym_at] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym__stmt] = STATE(2),
    [sym_action] = STATE(2),
    [sym_var_definition] = STATE(2),
    [sym_declaration] = STATE(2),
    [sym_trigger] = STATE(8),
    [sym_sequence] = STATE(57),
    [sym_repeat_quantifier] = STATE(41),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_sequence_repeat1] = STATE(13),
    [ts_builtin_sym_end] = ACTIONS(66),
    [sym_keyword] = ACTIONS(5),
    [sym_label] = ACTIONS(7),
    [sym_variable] = ACTIONS(9),
    [anon_sym_every] = ACTIONS(11),
    [anon_sym_at] = ACTIONS(13),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(6)] = {
    [sym_component_declaration] = STATE(25),
    [sym_events] = STATE(26),
    [sym_sequence] = STATE(51),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_sequence_repeat1] = STATE(13),
    [sym_keyword] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(68),
    [sym_label] = ACTIONS(70),
    [sym_variable] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(7)] = {
    [sym_events] = STATE(21),
    [sym_sequence] = STATE(51),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_sequence_repeat1] = STATE(13),
    [sym_keyword] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(72),
    [sym_label] = ACTIONS(70),
    [sym_variable] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(8)] = {
    [sym_events] = STATE(18),
    [sym_sequence] = STATE(51),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_sequence_repeat1] = STATE(13),
    [sym_keyword] = ACTIONS(5),
    [anon_sym_LBRACE] = ACTIONS(72),
    [sym_label] = ACTIONS(70),
    [sym_variable] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(9)] = {
    [sym_sequence] = STATE(52),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_events_repeat1] = STATE(11),
    [aux_sym_sequence_repeat1] = STATE(13),
    [sym_keyword] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(62),
    [sym_label] = ACTIONS(70),
    [sym_variable] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(10)] = {
    [sym_sequence] = STATE(52),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_events_repeat1] = STATE(10),
    [aux_sym_sequence_repeat1] = STATE(13),
    [sym_keyword] = ACTIONS(74),
    [anon_sym_RBRACE] = ACTIONS(77),
    [sym_label] = ACTIONS(79),
    [sym_variable] = ACTIONS(82),
    [sym_number] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(85),
    [anon_sym_LBRACK] = ACTIONS(88),
    [anon_sym_up] = ACTIONS(91),
    [anon_sym_down] = ACTIONS(91),
    [anon_sym_left] = ACTIONS(91),
    [anon_sym_right] = ACTIONS(91),
    [sym_color_value] = ACTIONS(94),
    [anon_sym_red] = ACTIONS(97),
    [anon_sym_green] = ACTIONS(97),
    [anon_sym_blue] = ACTIONS(97),
    [anon_sym_yellow] = ACTIONS(97),
    [anon_sym_black] = ACTIONS(97),
    [anon_sym_brown] = ACTIONS(97),
    [anon_sym_cyan] = ACTIONS(97),
    [anon_sym_purple] = ACTIONS(97),
    [anon_sym_orange] = ACTIONS(97),
    [anon_sym_white] = ACTIONS(97),
    [anon_sym_pink] = ACTIONS(97),
  },
  [STATE(11)] = {
    [sym_sequence] = STATE(52),
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(13),
    [sym_color_name] = STATE(24),
    [aux_sym_events_repeat1] = STATE(10),
    [aux_sym_sequence_repeat1] = STATE(13),
    [sym_keyword] = ACTIONS(5),
    [anon_sym_RBRACE] = ACTIONS(100),
    [sym_label] = ACTIONS(70),
    [sym_variable] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
  [STATE(12)] = {
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(12),
    [sym_color_name] = STATE(24),
    [aux_sym_sequence_repeat1] = STATE(12),
    [sym_keyword] = ACTIONS(102),
    [anon_sym_EQ] = ACTIONS(105),
    [anon_sym_SEMI] = ACTIONS(105),
    [sym_label] = ACTIONS(107),
    [sym_variable] = ACTIONS(110),
    [sym_number] = ACTIONS(110),
    [anon_sym_LPAREN] = ACTIONS(113),
    [anon_sym_LBRACK] = ACTIONS(116),
    [anon_sym_up] = ACTIONS(119),
    [anon_sym_down] = ACTIONS(119),
    [anon_sym_left] = ACTIONS(119),
    [anon_sym_right] = ACTIONS(119),
    [sym_color_value] = ACTIONS(122),
    [anon_sym_red] = ACTIONS(125),
    [anon_sym_green] = ACTIONS(125),
    [anon_sym_blue] = ACTIONS(125),
    [anon_sym_yellow] = ACTIONS(125),
    [anon_sym_black] = ACTIONS(125),
    [anon_sym_brown] = ACTIONS(125),
    [anon_sym_cyan] = ACTIONS(125),
    [anon_sym_purple] = ACTIONS(125),
    [anon_sym_orange] = ACTIONS(125),
    [anon_sym_white] = ACTIONS(125),
    [anon_sym_pink] = ACTIONS(125),
  },
  [STATE(13)] = {
    [sym_position] = STATE(17),
    [sym_vector] = STATE(17),
    [sym_direction] = STATE(17),
    [sym_color] = STATE(17),
    [sym_value] = STATE(12),
    [sym_color_name] = STATE(24),
    [aux_sym_sequence_repeat1] = STATE(12),
    [sym_keyword] = ACTIONS(128),
    [anon_sym_EQ] = ACTIONS(130),
    [anon_sym_SEMI] = ACTIONS(130),
    [sym_label] = ACTIONS(132),
    [sym_variable] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_up] = ACTIONS(21),
    [anon_sym_down] = ACTIONS(21),
    [anon_sym_left] = ACTIONS(21),
    [anon_sym_right] = ACTIONS(21),
    [sym_color_value] = ACTIONS(23),
    [anon_sym_red] = ACTIONS(25),
    [anon_sym_green] = ACTIONS(25),
    [anon_sym_blue] = ACTIONS(25),
    [anon_sym_yellow] = ACTIONS(25),
    [anon_sym_black] = ACTIONS(25),
    [anon_sym_brown] = ACTIONS(25),
    [anon_sym_cyan] = ACTIONS(25),
    [anon_sym_purple] = ACTIONS(25),
    [anon_sym_orange] = ACTIONS(25),
    [anon_sym_white] = ACTIONS(25),
    [anon_sym_pink] = ACTIONS(25),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(5), 1,
      sym_keyword,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_color_value,
    ACTIONS(70), 1,
      sym_label,
    STATE(24), 1,
      sym_color_name,
    STATE(58), 1,
      sym_sequence,
    ACTIONS(15), 2,
      sym_variable,
      sym_number,
    STATE(13), 2,
      sym_value,
      aux_sym_sequence_repeat1,
    ACTIONS(21), 4,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
    STATE(17), 4,
      sym_position,
      sym_vector,
      sym_direction,
      sym_color,
    ACTIONS(25), 11,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [55] = 6,
    ACTIONS(11), 1,
      anon_sym_every,
    ACTIONS(13), 1,
      anon_sym_at,
    STATE(7), 1,
      sym_trigger,
    STATE(41), 1,
      sym_repeat_quantifier,
    ACTIONS(136), 8,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(134), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [96] = 10,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_color_value,
    ACTIONS(138), 1,
      anon_sym_RBRACK,
    STATE(24), 1,
      sym_color_name,
    STATE(45), 1,
      sym_value,
    ACTIONS(15), 2,
      sym_variable,
      sym_number,
    ACTIONS(140), 4,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
    STATE(17), 4,
      sym_position,
      sym_vector,
      sym_direction,
      sym_color,
    ACTIONS(142), 11,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [144] = 2,
    ACTIONS(146), 10,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_color_value,
    ACTIONS(144), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [175] = 2,
    ACTIONS(148), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(150), 18,
      sym_keyword,
      anon_sym_every,
      anon_sym_at,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [206] = 2,
    ACTIONS(154), 10,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_color_value,
    ACTIONS(152), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [237] = 2,
    ACTIONS(158), 10,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_color_value,
    ACTIONS(156), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [268] = 2,
    ACTIONS(160), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(162), 18,
      sym_keyword,
      anon_sym_every,
      anon_sym_at,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [299] = 9,
    ACTIONS(17), 1,
      anon_sym_LPAREN,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      sym_color_value,
    STATE(24), 1,
      sym_color_name,
    STATE(48), 1,
      sym_value,
    ACTIONS(15), 2,
      sym_variable,
      sym_number,
    ACTIONS(140), 4,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
    STATE(17), 4,
      sym_position,
      sym_vector,
      sym_direction,
      sym_color,
    ACTIONS(142), 11,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [344] = 2,
    ACTIONS(164), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(166), 18,
      sym_keyword,
      anon_sym_every,
      anon_sym_at,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [375] = 2,
    ACTIONS(170), 10,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_color_value,
    ACTIONS(168), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [406] = 2,
    ACTIONS(172), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(174), 18,
      sym_keyword,
      anon_sym_every,
      anon_sym_at,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [437] = 2,
    ACTIONS(176), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(178), 18,
      sym_keyword,
      anon_sym_every,
      anon_sym_at,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [468] = 2,
    ACTIONS(180), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(182), 18,
      sym_keyword,
      anon_sym_every,
      anon_sym_at,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [499] = 2,
    ACTIONS(186), 10,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_color_value,
    ACTIONS(184), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [530] = 2,
    ACTIONS(188), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(190), 18,
      sym_keyword,
      anon_sym_every,
      anon_sym_at,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [561] = 2,
    ACTIONS(194), 10,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_color_value,
    ACTIONS(192), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [592] = 2,
    ACTIONS(198), 10,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_color_value,
    ACTIONS(196), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [623] = 2,
    ACTIONS(202), 10,
      anon_sym_EQ,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_color_value,
    ACTIONS(200), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [654] = 2,
    ACTIONS(204), 8,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(206), 18,
      sym_keyword,
      anon_sym_every,
      anon_sym_at,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [685] = 3,
    ACTIONS(208), 1,
      anon_sym_EQ,
    ACTIONS(146), 7,
      anon_sym_SEMI,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(144), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [716] = 2,
    ACTIONS(213), 7,
      anon_sym_LBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(211), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [744] = 2,
    ACTIONS(217), 7,
      anon_sym_LBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(215), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [772] = 2,
    ACTIONS(221), 7,
      anon_sym_LBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(219), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [800] = 2,
    ACTIONS(225), 7,
      anon_sym_LBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(223), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [828] = 2,
    ACTIONS(77), 7,
      anon_sym_RBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(227), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [856] = 2,
    ACTIONS(231), 7,
      anon_sym_LBRACE,
      sym_label,
      sym_variable,
      sym_number,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_color_value,
    ACTIONS(229), 16,
      sym_keyword,
      anon_sym_up,
      anon_sym_down,
      anon_sym_left,
      anon_sym_right,
      anon_sym_red,
      anon_sym_green,
      anon_sym_blue,
      anon_sym_yellow,
      anon_sym_black,
      anon_sym_brown,
      anon_sym_cyan,
      anon_sym_purple,
      anon_sym_orange,
      anon_sym_white,
      anon_sym_pink,
  [884] = 8,
    ACTIONS(233), 1,
      sym_number,
    ACTIONS(235), 1,
      anon_sym_frame,
    ACTIONS(237), 1,
      anon_sym_frames,
    ACTIONS(241), 1,
      anon_sym_seconds,
    ACTIONS(245), 1,
      anon_sym_millisecond,
    STATE(40), 1,
      sym_time_unit,
    ACTIONS(239), 2,
      anon_sym_s,
      anon_sym_second,
    ACTIONS(243), 2,
      anon_sym_ms,
      anon_sym_milliseconds,
  [911] = 2,
    ACTIONS(249), 4,
      anon_sym_frame,
      anon_sym_s,
      anon_sym_second,
      anon_sym_millisecond,
    ACTIONS(247), 5,
      sym_number,
      anon_sym_frames,
      anon_sym_seconds,
      anon_sym_ms,
      anon_sym_milliseconds,
  [925] = 7,
    ACTIONS(235), 1,
      anon_sym_frame,
    ACTIONS(237), 1,
      anon_sym_frames,
    ACTIONS(241), 1,
      anon_sym_seconds,
    ACTIONS(245), 1,
      anon_sym_millisecond,
    STATE(36), 1,
      sym_time_unit,
    ACTIONS(239), 2,
      anon_sym_s,
      anon_sym_second,
    ACTIONS(243), 2,
      anon_sym_ms,
      anon_sym_milliseconds,
  [949] = 2,
    ACTIONS(253), 4,
      anon_sym_frame,
      anon_sym_s,
      anon_sym_second,
      anon_sym_millisecond,
    ACTIONS(251), 5,
      sym_number,
      anon_sym_frames,
      anon_sym_seconds,
      anon_sym_ms,
      anon_sym_milliseconds,
  [963] = 3,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(257), 1,
      anon_sym_RBRACK,
    STATE(46), 1,
      aux_sym_vector_repeat1,
  [973] = 3,
    ACTIONS(255), 1,
      anon_sym_COMMA,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
    STATE(47), 1,
      aux_sym_vector_repeat1,
  [983] = 3,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    ACTIONS(264), 1,
      anon_sym_RBRACK,
    STATE(47), 1,
      aux_sym_vector_repeat1,
  [993] = 1,
    ACTIONS(264), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [998] = 2,
    ACTIONS(266), 1,
      anon_sym_EQ,
    ACTIONS(268), 1,
      anon_sym_SEMI,
  [1005] = 1,
    ACTIONS(270), 1,
      sym_number,
  [1009] = 1,
    ACTIONS(62), 1,
      anon_sym_SEMI,
  [1013] = 1,
    ACTIONS(268), 1,
      anon_sym_SEMI,
  [1017] = 1,
    ACTIONS(272), 1,
      sym_number,
  [1021] = 1,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
  [1025] = 1,
    ACTIONS(276), 1,
      anon_sym_RPAREN,
  [1029] = 1,
    ACTIONS(278), 1,
      anon_sym_COMMA,
  [1033] = 1,
    ACTIONS(266), 1,
      anon_sym_EQ,
  [1037] = 1,
    ACTIONS(280), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 55,
  [SMALL_STATE(16)] = 96,
  [SMALL_STATE(17)] = 144,
  [SMALL_STATE(18)] = 175,
  [SMALL_STATE(19)] = 206,
  [SMALL_STATE(20)] = 237,
  [SMALL_STATE(21)] = 268,
  [SMALL_STATE(22)] = 299,
  [SMALL_STATE(23)] = 344,
  [SMALL_STATE(24)] = 375,
  [SMALL_STATE(25)] = 406,
  [SMALL_STATE(26)] = 437,
  [SMALL_STATE(27)] = 468,
  [SMALL_STATE(28)] = 499,
  [SMALL_STATE(29)] = 530,
  [SMALL_STATE(30)] = 561,
  [SMALL_STATE(31)] = 592,
  [SMALL_STATE(32)] = 623,
  [SMALL_STATE(33)] = 654,
  [SMALL_STATE(34)] = 685,
  [SMALL_STATE(35)] = 716,
  [SMALL_STATE(36)] = 744,
  [SMALL_STATE(37)] = 772,
  [SMALL_STATE(38)] = 800,
  [SMALL_STATE(39)] = 828,
  [SMALL_STATE(40)] = 856,
  [SMALL_STATE(41)] = 884,
  [SMALL_STATE(42)] = 911,
  [SMALL_STATE(43)] = 925,
  [SMALL_STATE(44)] = 949,
  [SMALL_STATE(45)] = 963,
  [SMALL_STATE(46)] = 973,
  [SMALL_STATE(47)] = 983,
  [SMALL_STATE(48)] = 993,
  [SMALL_STATE(49)] = 998,
  [SMALL_STATE(50)] = 1005,
  [SMALL_STATE(51)] = 1009,
  [SMALL_STATE(52)] = 1013,
  [SMALL_STATE(53)] = 1017,
  [SMALL_STATE(54)] = 1021,
  [SMALL_STATE(55)] = 1025,
  [SMALL_STATE(56)] = 1029,
  [SMALL_STATE(57)] = 1033,
  [SMALL_STATE(58)] = 1037,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [116] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [119] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [125] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_sequence_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sequence, 1, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_sequence_repeat1, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sequence_repeat1, 1, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 2, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_direction, 1, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_direction, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 2, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_action, 3, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_action, 3, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_events, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_events, 2, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color, 1, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 6),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 3, 0, 6),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 3, 0, 7),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 3, 0, 7),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_definition, 4, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_var_definition, 4, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 4, 0, 0),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 4, 0, 0),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_events, 3, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_events, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_vector, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_vector, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_color_name, 1, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_color_name, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_position, 5, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_position, 5, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration, 3, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration, 3, 0, 0),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_value, 1, 0, 0), SHIFT(14),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_time_unit, 1, 0, 3),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_unit, 1, 0, 3),
  [215] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger, 3, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 3, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_time_unit, 1, 0, 4),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_unit, 1, 0, 4),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_time_unit, 1, 0, 5),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_time_unit, 1, 0, 5),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_events_repeat1, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trigger, 2, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trigger, 2, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repeat_quantifier, 1, 0, 2),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_repeat_quantifier, 1, 0, 2),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_repeat_quantifier, 1, 0, 1),
  [253] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_repeat_quantifier, 1, 0, 1),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_vector_repeat1, 2, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [274] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_vinx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_keyword,
    .primary_state_ids = ts_primary_state_ids,
    .name = "vinx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
